### ISSUE TITLE
Refactor Application Controller

### ISSUE THREAD

**Issue by Ciaran0** [CommunityRoots/Transparent-Donation-System#16]
Separate logic. Application controller becoming too big.
Create Login controller, forgot password controller etc

**Comment by davidcampbelloconnor** [comment]
Is there any easy way to do this?
Or would we have to change Application.login() to Login.login() in all of our views?

**Comment by Ciaran0** [comment]
Dont think theres a very easy way to do this.
Can use intelliJ refactoring tools to help a bit

Application controller isnt too bad
maybe just separate out needs stuff? just makes more sense
Profile controller has gotten huge

**Comment by davidcampbelloconnor** [comment]
I'm thinking about doing something like this:
Move all needs stuff from application to new controller need
Move all login stuff from application to new controller login
Leave basic pages like index, need, etc in application

Will I separate the profile controller too?

**Comment by Ciaran0** [comment]
Yeah sounds good!
Will make testing make more sense too.
I can work on profile tomorrow as well

**Comment by davidcampbelloconnor** [comment]
I can refactor profile stuff now? 

What should I move?
