### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by Ciaran0** [CommunityRoots/Transparent-Donation-System#29]
At the moment we use strings "admin" "volunteer" and "user"

Possible should change to int to make access level control easier 
eg) instead of if(user.role.equals("admin") || user.role.equals("volunteer"))
if(user.role >1)

Probably should have some level that adds admins.
these admins can then add volunteers to their charity who add the needs

**Comment by davidcampbelloconnor** [comment]
Yeah we should do all that.

**Comment by davidcampbelloconnor** [comment]
Maybe the roles could be
1 - admin adder
2 - community admin
3 - volunteer
4 - donator account
