### ISSUE TITLE
Charity table

### ISSUE THREAD

**Issue by davidcampbelloconnor** [CommunityRoots/Transparent-Donation-System#32]
Maybe we should add a charity table to our database to store the volunteers and their respective communities. At the moment, an admin listing their community's volunteers will list every member of that charity regardless of location.

**Comment by Ciaran0** [comment]
Think this links in with #29 
Highest level user call it management for the moment (us two) can add charities to the Database. Then we add an admin to that charity and then they can add volunteers.
Charity could be a separate model entirely

**Comment by davidcampbelloconnor** [comment]
Yeah grand.
