### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by Ciaran0** [CommunityRoots/Transparent-Donation-System#7]
Rep can send out updates about a certain need they added.
eg) tom now can go back to college.
|| toms condition is now worse please donate

Database table would have to be added

**Comment by davidcampbelloconnor** [comment]
Volunteers could add updates on the editNeed page maybe.

Update could
- be sent to donators to that need through email
- be shown on viewNeed page

**Comment by Ciaran0** [comment]
Yeah Sounds good

**Comment by Ciaran0** [comment]
Donators should be able to subscribe/ unsubscribe to updates to a particular need.

**Comment by davidcampbelloconnor** [comment]
Making updates through editNeed page actually was working but now its not. It's not just updates though, we can't edit needs at all at the moment. Don't know why.

Haven't got changing subscriptions working yet - it's probably because I have something wrong in the profile controller.

**Comment by Ciaran0** [comment]
It should be working now?
where do the users get the option to opt out of email updates?

**Comment by Ciaran0** [comment]
Email of update should probably have a link to where they can unsubscribe from

**Comment by davidcampbelloconnor** [comment]
Yeah it works! Yeah on the settings page and on the email - we can put the link in when we implement emails through html.
